services:
  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    volumes:
      - './app-api:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - ES_URL=https://recommendations-service.es.europe-west1.gcp.cloud.es.io:9243
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=dukc9ANY2lf7CG5ID3FHO3sa
  client:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    volumes:
      - './app-ui:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - NEXT_API_URL=http://api:8000
    depends_on:
      - api
