services:
  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    image: api_image:${BRANCH_NAME:-latest}
    volumes:
      - './app-api:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - ES_URL=http://kubernetes-vm:30920
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    command: ["sh", "-c", "sleep 10 && curl -X GET 'http://localhost:3000/api/search/search-movies?q=book&hybrid=false&type=bm25&dataset=movies'"]
  client:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    image: client_image:${BRANCH_NAME:-latest}
    volumes:
      - './app-ui:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - NEXT_API_URL=http://api:8000
    depends_on:
      - api
