services:
  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    image: api_image:${BRANCH_NAME:-latest}
    volumes:
      - './app-api:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - ES_URL=http://kubernetes-vm:30920
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    healthcheck:  
      test: ["CMD", "sh", "-c", "curl -f -u $ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD -H 'Content-Type: application/json' -d '{\"params\": {\"query_string\": \"spirited away\"}}' $ES_URL/_application/search_application/text-search/_search"]
      interval: 30s  
      timeout: 10s  
      retries: 5  
  client:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    image: client_image:${BRANCH_NAME:-latest}
    volumes:
      - './app-ui:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - NEXT_API_URL=http://api:8000
    depends_on:
      - api
